### ISSUE TITLE
pdf.pdf找不到

### ISSUE THREAD

**Issue by Dmomoko** [cjhdevact/FlyEduDownloader#2]
是不是更新了规则，加密了这个元素？（猜测）
还有其他方法查看X-Nd-Auth吗？

**Comment by cjhdevact** [comment]
对于某些电子课本(例如高中语文人教版教材),它的文件名是(课本名称).pdf,如果没有pdf.pdf,注意找pdf结尾的文件,特别是文件名以%XX%XX开头的文件,当时测试没有测试高中课本,现在才发现的.

**Comment by cjhdevact** [comment]
如果你是等加载完成再打开开发者工具的,请打开后重新刷新一下网页
